spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      jakarta.persistence.validation.group.pre-persist: org.example.restaurantvoting.common.validation.View$Persist
      jakarta.persistence.validation.group.pre-update: org.example.restaurantvoting.common.validation.View$Persist
  datasource:
    url: jdbc:h2:mem:restaurant_voting
    username: sa
    password:
  cache:
    cache-names: restaurants
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

logging:
  level:
    root: WARN
    org.example.restaurantvoting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework.cache: TRACE

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

springdoc.swagger-ui.path: /